# Generated by Django 5.0.2 on 2025-04-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='descrition',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='descrition',
            new_name='description',
        ),
    ]
